keys = {
  TWITTER_CONSUMER_KEY: 'G9Wa85cKomo2ytL9JOEtPqHVX',
  TWITTER_CONSUMER_SECRET: 'NKS6HoLdJSe0Z3iTfq4CjWurxPAMisjy4NkkDt3by7Vgm2QbfR',
  TWITTER_ACCESS_TOKEN_KEY: '',
  TWITTER_ACCESS_TOKEN_SECRET: ''
}
